"""Visualization settings preserved from the current frozen main recipes."""

STAGE_VISUALIZATION = {1: {'prediction_glb': {'enabled': True,
                        'every_epochs': 1,
                        'export_final': True,
                        'base_sample': 'mesh',
                        'action_units': [0, 8, 10, 20, 22, 26, 45, 52],
                        'output_convention': 'metahuman',
                        'step_snapshot': {'enabled': True,
                                          'every_steps': 1000,
                                          'log_render_to_wandb': True,
                                          'log_glb_to_wandb': True,
                                          'max_wandb_glbs': 5},
                        'smoothing': {'iterations': 0, 'blend': 0.25, 'max_edges': 1000000},
                        'surface_smoothing': {'enabled': False,
                                              'iterations': 0,
                                              'blend': 0.2,
                                              'max_edges': 1000000}},
     'visualization': {'mesh_up_axis': 'z',
                       'custom_mesh_input_convention': 'custom-glb-y-up-neg-z-front',
                       'custom_mesh_align_to_metahuman': True,
                       'custom_mesh_blender': None,
                       'custom_mesh_refresh_landmarks': False,
                       'custom_mesh_min_alignment_landmarks': 32,
                       'custom_mesh_alignment_mode': 'scale_translation',
                       'action_units': [0, 8, 10, 20, 22, 26, 45, 52],
                       'base_sample': 'mesh'}},
 2: {'prediction_glb': {'enabled': True,
                        'every_epochs': 1,
                        'export_final': True,
                        'base_sample': 'image',
                        'action_units': [8, 9, 10, 11, 20, 21, 22, 23],
                        'output_convention': 'metahuman',
                        'render_png': True,
                        'render_png_name': 'prediction_render.png',
                        'step_snapshot': {'enabled': True,
                                          'every_steps': 10000,
                                          'log_render_to_wandb': True,
                                          'log_glb_to_wandb': True,
                                          'max_wandb_glbs': 5},
                        'smoothing': {'iterations': 0, 'blend': 0.25, 'max_edges': 1000000},
                        'surface_smoothing': {'enabled': False,
                                              'iterations': 0,
                                              'blend': 0.2,
                                              'max_edges': 1000000}},
     'visualization': {'mesh_up_axis': 'z',
                       'base_sample': 'image',
                       'custom_mesh_input_convention': 'custom-glb-y-up-neg-z-front',
                       'custom_mesh_align_to_metahuman': True,
                       'custom_mesh_blender': None,
                       'custom_mesh_refresh_landmarks': False,
                       'custom_mesh_min_alignment_landmarks': 32,
                       'custom_mesh_alignment_mode': 'scale_translation',
                       'action_units': [8, 9, 10, 11, 20, 21, 22, 23]}}}
